### ISSUE TITLE
Support for Localization

### ISSUE THREAD

**Issue by sh977218** [sylvanaar/wow-instant-messenger#4] opened 2019-12-11 01:55 UTC
Hi,
Does WIM support languages other than English? Like Korean, Japanese or Chinese.

**Comment by sh977218** [comment] 2019-12-11 03:26
If the game client is in English, you can't see Chinese typing in VIM. But if you switch game client to Chinese, it works. Is this intended to do?

**Comment by MysticalOS** [comment] 2019-12-11 03:30
That's not a limitation of WIM but of font you are using. you have to be using a font that supports chinese characters. I think wim lets you change font, not sure. it chooses the default font based on what default font client is using, and when set to english that'd be the non unicode english font. This is something I've not had to deal with really so I haven't played with it at all.

**Comment by sh977218** [comment] 2019-12-11 23:16
@MysticalOS Thanks for the information. Is there anyway to change WIM's unicode?

**Comment by sh977218** [comment] 2019-12-11 23:45
I tried to change fonts, but it didn't work. I don't think the problem is related to font.
I'm able to see the correct Chinese character in history view, Chat View, Text View, BBCode and HTML. But I'm not able to see the correct character in the chat window...

**Comment by Pazza** [comment] 2019-12-12 22:07
Trying toggling through different fonts in WIM's settings. I'm sure its because you are using a font that doesn't support the characters. We don't do any special manipulation besides allowing you to select which one is assigned to scrolling chat frame widget.

**Comment by sh977218** [comment] 2019-12-19 19:23
I've tried all the fonts in settings, none of them works. When I check the game client to be Chinese, WIM doesn't have fonts selection options. Is changing fonts only available in English?

**Comment by Pazza** [comment] 2019-12-20 11:52
WIM offers fonts found in SharedMediaLibrary. If a font isn't listed, it hasn't been registered to the library. WIM itself doesn't register fonts I believe. If no fonts are found, it falls back to the game client's default chat font.

**Comment by zhaodadi** [comment] 2020-04-09 12:24
yeah, i can send Chinese message to others but not able to receive Chinese characters.

**Comment by zhaodadi** [comment] 2020-04-09 12:49
i can confirm by changing to a font that supports Chinese worked. 
Here is a link to a font i used for testing

https://github.com/nowar-fonts/Nowar-Sans

**Comment by Pazza** [comment] 2020-08-04 22:24
Considering this not to be a bug.

**Closed by Pazza** 2020-08-04 22:24 UTC
